module.exports = {
    AbstractTTS: require("./src/abstract-tts"),
    AudioTrans: require("./src/audio-trans"),
    AudioUrls: require("./src/audio-urls"),
    //ContentUpdater: require('./src/content-updater'),
    HumanTts: require("./src/human-tts"),
    //MdAria: require("./src/md-aria"),
    Playlist: require('./src/playlist'),
    Polly: require("./src/polly"),
    //S3Bucket: require('./src/s3-bucket'),
    S3Creds: require('./src/s3-creds'),
    SCAudio: require('./src/sc-audio'),
    //ScvRest: require('./src/scv-rest'),
    SectionParser: require('./src/section-parser'),
    Section: require('./src/section'),
    SoundStore: require('./src/sound-store'),
    SuttaDuration: require("./src/sutta-duration"),
    SuttaFactory: require("./src/sutta-factory"),
    Sutta: require("./src/sutta"),
    SuttaStore: require('./src/sutta-store'),
    Task: require('./src/task'),
    VoiceFactory: require('./src/voice-factory'),
    Voice: require('./src/voice'),
    //VsmStore: require('./src/vsm-store'),
    //Watson: require("./src/watson"),
    Words: require('./src/words'),

};
